### ISSUE TITLE
[BUG] 部分主页图标无限刷新(闪烁)

### ISSUE THREAD

**Issue by leviolet** [zjgsuzjx/acg#1]
您好,MyACG我经常使用的一个网站
最近我在网站主页中发现无法加载远程URL的图标在使用本地"无图"favicon.png文件时,无法正确加载，如附图所示。
这可能对网站的性能影响较大,表现为在我的低端(Atom 平板)设备上会比较卡。（而且容易闪瞎眼
网站自带的反馈功能无法使用，所以提了issue

## 复现

api.iowen.cn对应图标没有或无法访问时，如(8月14日的)A-zmanga

## 推测

个人推测是```index.html```中各个站点的图标代码:

```html
<img class="lazy" src="/acg/wp-content/themes/webstackpro/images/favicon.png" data-src="https://api.iowen.cn/favicon/steamgalgame.com.png" onerror="javascript:this.src='/wp-content/themes/webstackpro/images/favicon.png'">
```

中的```onerror```属性没有正确填写
在```https://api.iowen.cn/favicon/steamgalgame.com.png```无法访问时，应该会触发```onerror```，加载```/wp-content/themes/webstackpro/images/favicon.png```，但```/wp-content/themes/webstackpro/images/favicon.png```地址不正确会导致再次发生错误，触发```onerror```，从而不断循环

## 建议

在index.html中, 将所有的```onerror="javascript:this.src='/wp-content/themes/webstackpro/images/favicon.png'"```
替换为```onerror="javascript:this.src='/acg/wp-content/themes/webstackpro/images/favicon.png'"```

在我的浏览器上成功解决了这个问题

### 环境

Windows 10 x64
Microsoft Edge 92

### BUG截图

![屏幕截图 2021-08-14 073150](https://user-images.githubusercontent.com/54400030/129427097-fa9163c3-1104-4dcc-96f0-5d18ac9615fa.jpg)

**Comment by zjgsuzjx** [comment]
感谢反馈与修改建议，已解决。
