### ISSUE TITLE
[BUG] Gitalk评论功能在MyACG上用Github登录时出现404

### ISSUE THREAD

**Issue by leviolet** [zjgsuzjx/acg#5]
## 复现

在博主的另一个网站CS_MD上Gitalk评论功能正常,在MyACG上会显示`404 The site configured at this address does not contain the requested file.`

![Gitalk BUG](https://user-images.githubusercontent.com/54400030/152990069-1b161336-8237-4749-a128-8fa6a4d3cb27.gif)
![Gitalk BUG 2](https://user-images.githubusercontent.com/54400030/152990080-dd8b0c7a-940f-485a-a51f-9e5116771a5d.gif)

## 可能的解决方法

未经测试,只是根据以往搭博客的经验想到的。

建议检查一下当初在Github后台的[OAuth application(以前是这个位置,后来可能有改动)](https://github.com/settings/developers)设置Authorization callback URL的时候是不是写成了`https://zjgsuzjx.github.io/CS_MD/`没有包含`https://zjgsuzjx.github.io/acg/`。
如果想两个地址都能用的话可以不带路径: `https://zjgsuzjx.github.io/`

## 环境

Windows 10 x64
Microsoft Edge 98

**Comment by zjgsuzjx** [comment]
已解决，感谢提出，确实是回调地址错了
